apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  replicas: {{ .Values.angular.replicas }}
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: {{ .Values.angular.image }}
          ports:
            - containerPort: 80
