apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: {{ .Values.fastapi.service.type }}
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
